routes/admin.php
<?php

Route::group(['prefix' => 'inicio', 'as' => 'inicio.'], function() {
    Route::get('/', ['as' => 'index', 'uses' => 'InicioController@index']);
    
});



Route::group(['prefix' => 'nosotros', 'as' => 'nosotros.'], function() {
    Route::get('/', ['as' => 'index', 'uses' => 'NosotrosController@index']);

    
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
use Illuminate\Http\Request;

use App\Models\Incidente;

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index');

Route::get('/departamento/{departamento}/provincias', ['as' => 'getProvincias', 'uses' => 'ProvinciaController@getByDepartamento']);
Route::get('/provincia/{provincia}/distritos', ['as' => 'getDistritos', 'uses' => 'DistritoController@getByProvincia']);

Route::get('/listar_incidentes',function(){
    return Incidente::all();
});

app/Models/TipoUsuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TipoUsuario extends Model
{
    protected $table = 'tipo_usuario';

    protected $fillable = [
        'id',
        'nombre'
    ];

    public $timestamps = false;

    public function users()
    {
        return $this->hasMany(Usuario::class);
    }
}

app/Models/Usuario.php
<?php

namespace App\Models;

use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Usuario extends Authenticatable
{
    use Notifiable, SoftDeletes, HasApiTokens;

    protected $table = 'usuario';

    protected $fillable = [
        'id',
        'nombres',
        'apellidos',
        'email',
        'password',
        'tipo_usuario_id',
    ];

    protected $hidden = [
        'password',
        'remember_token'
    ];

    protected $dates = [
        'deleted_at'
    ];

    public $timestamps = false;

    public function alumno()
    {
        return $this->hasOne(Alumno::class, 'id');
    }

    public function docente()
    {
        return $this->hasOne(Docente::class, 'id');
    }

    public function attendances()
    {
        return $this->hasMany(Attendance::class);
    }

    public function tipo_usuario()
    {
        return $this->belongsTo(TipoUsuario::class);
    }

    

    public function scopeWhereAdmin($query)
    {
        return $query->where('tipo_usuario_id', 1);
    }

    public function getNombreCompletoAttribute()
    {
        return ucfirst($this->nombres) . " " . ucfirst($this->apellidos);
    }

    public function getEsAdminAttribute()
    {
        return $this->tipo_usuario_id == 1;
    }

    public function getEsDocenteAttribute()
    {
        return $this->tipo_usuario_id == 3;
    }
}

app/Http/Controllers/Admin/BaseAdminController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class BaseAdminController extends Controller
{
    /**
      * Descripcion: Ruta hacia el indice del recurso
      * @var string
      */
    protected $index_route;

    /**
     * Redireccion hacia el indice del recurso
     * @param string $mensaje
     * @param array $params Arreglo de ids o prefix que se necesite para llegar al index
     * @return type
     */
    protected function redirectToIndex($mensaje, $params = [])
    {
        if ($this->index_route)
            return redirect()
                 ->route($this->index_route, $params)
                 ->with(['message' => $mensaje]);
    }
}

app/Http/Controllers/Admin/InicioController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\BaseAdminController;



class InicioController extends BaseAdminController
{
    protected $index_route = 'inicio.index';

    public function index()
    {
        

        return view('admin.inicio.index');
    }
}

app/Http/Controllers/Admin/NosotrosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\BaseAdminController;


use App\Models\Usuario;



class NosotrosController extends BaseAdminController
{
    public $index_route = 'nosotros.index';

    public function index()
    {

        return view('admin.nosotros.index');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        if ($user->esAdmin) {
            return redirect()->route('instituciones.index');
        } elseif ($user->esDocente) {
            return redirect()->route('grupos.index');
        }
    }
}

resources/views/admin/inicio/index.blade.php
@extends('layouts.admin')

@section('content')

    

    <div class="row" id="app">
        <div class="panel panel-info">
            <div class="panel-heading text-center">
                <h3>Inicio</h3>
            </div>
            <div class="panel-body">
                <div class="panel-heading text-center" id="column"><!-- column -->
                    <div class="panel-body" id="content"><!-- content -->
                      <h3>Qué es Maranguita</h3>                      
                      <p><span id="quees">Maranguita es un Movimiento de Educación Popular Integral y Promoción Social,  basado en los valores de justicia, libertad, participación y fraternidad, dirigida a la población empobrecida y excluida para contribuir a la transformación de las sociedades.</span></p>
                      <p>&nbsp;</p>

                      <h2>Misión</h2>
                      <p class="lead" >Brindar una educación pública de calidad desde los valores evangélicos, con el propósito de contribuir a la formación de ciudadanos capaces de mejorar sus condiciones de vida y la transformación de las sociedades.</p>
                      <p>&nbsp;</p>
                      <h3>Visión</h3>
                    </div>
                    <div class="panel-body" id="vision"><!-- group -->
                        
                           <p>Ser referente válido para la educación pública.</p>
                           <p>Implementar una propuesta educativa sistematizada que responda a las necesidades de los excluidos.</p>
                           <p>Formar ciudadanos éticos, democráticos y comprometidos con la transformación de la sociedad y el desarrollo sostenible.</p>
                        
                    </div>    
                </div>
            </div>    
            
        </div>
    </div>
@endsection

resources/views/admin/nosotros/index.blade.php
@extends('layouts.admin')

@section('content')

    

    <div class="row">
                <h1 class="page-title text-center">Centro de Rehabilitacion Juvenil XD</h1>
                <hr>
                <div class="col-lg-4 col-sm-4">
                    
                        

                            <img src="imagenes/maranguitaCole.jpg">   
                                              
                   
                </div>
                <div class="col-lg-8 col-sm-8">
                    <h2>¿QUIÉNES SOMOS?</h2>
                    <p class="lead">
                        Maranguita es un colegio que trabaja con mucho labor y 
                        una amplia experiencia en el ámbito de pedagogia. Somos una colegio que enseña valores
                        y futuros pirañas :D:
                    <strong>
                        Cumplir con las aprendizaje del alumno y este se sienta conforme con nuestra trabajo.
                    </strong>
                    </p>
                    <p class="lead">
                        Operamos conforme a las necesidades que el padre requiera de nuestro servicio, analisamos detalle a detalle
                         lo que el cliente pide.
                    </p>
                    <div class="space"></div>
                </div>
            </div>
            <div class= "row">
                <div class="col-md-12">
                    <hr>
                    <h2>¿Qué servicios brindamos?</h2>
                    <ul class="list-icons lead">
                        <li>
                            <i class="icon-check">
                            </i>
                            Brindamos el servicio de escuela de Padres.
                        </li>
                        <li>
                            <i class="icon-check">
                            </i>
                            Brindamos servicio de talleres pedagogicos.
                        </li>
                        <li>
                            <i class="icon-check">
                            </i>
                            Contamos con el servicio de tutoria.
                        </li>
                        <li>
                            <i class="icon-check">
                            </i>
                            También contamos con el servicio psicologia educativa.
                        </li>
                        <li>
                            <i class="icon-check">
                            </i>
                            Disponemos del servicio de formacion vocacional.
                        </li>
                       
                    </ul>
                </div>
            </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="shortcut icon" href="{{ url('favicon.ico') }}" />

    <!-- Styles -->
    <link href="{{ url('css/app.css') }}" rel="stylesheet">
    <link href="{{ url('css/admin.css') }}" rel="stylesheet" >

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top navbar-bottom-0">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->nombre_completo }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>

        </div>
    </nav>

    @if( Auth::user()->tipo_usuario_id == 1 )
        @include('layouts.admin_sidebar')
    @elseif( Auth::user()->tipo_usuario_id == 3 )
        @include('layouts.docente_sidebar')
    @endif

    <script src="{{ url('js/app.js') }}"></script>
    <script>
        window.app_url = "{{ url('/') }}";
    </script>

    <div class="content">
        @yield('content')
    </div>
    <!-- Scripts -->
    @stack('scripts')
</body>
</html>

resources/views/layouts/admin_sidebar.blade.php
   <div class="container" >
        <div class="navbar-header" >

           <input type="hidden" name="_token" value="2">

          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse" >
          <ul class="nav navbar-nav">
            <li ><a href="{{ route('inicio.index') }}" <i class="icon fa fa-university fa-2x" aria-hidden="true"></i>Inicio</a></li>
            <li ><a href="{{ route('nosotros.index') }}" <i class="icon fa fa-university fa-2x" aria-hidden="true"></i>Nosotros</a></li>
            <li ><a href="catalogo">Admisiones</a></li>
            <li ><a href="ubicacion">Encuestas</a></li>
            <li ><a href="contactenos">Contáctenos</a></li>
            
          </ul>
        </div>
      </div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{ url('favicon.ico') }}" />

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ url('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" >
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- Scripts -->
    <script src="{{ url('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/docente_sidebar.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="navbar-collapse collapse">
    <ul class="nav in">
        <li>
            <a class="sidebar-link" href="{{ route('grupos.index') }}">Grupos</a>
        </li>
    </ul>
    </div>
</div>

resources/views/syllabus.blade.php
@extends('layouts.app')

@section('content')

<script src="{{ url('js/app.js') }}"></script>
<style type="text/css">
    .clickable {
        cursor: pointer;
    }
    .unidad-selected {
    }
    .semana-selected {
        background: #fc0;
    }
    #unidades {
        margin-top: 15px;
        text-align: center;
    }
    #unidades .unidad {
        width: 50%;
        margin: 0 auto;
    }
    .unidad p {
        line-height: 40px;
        margin: 0px;
    }
    .unidad-selected p {
        background-color:  #d6dac6;
        color: #000;
    }
    .column {
        border-right: #fcf solid 2px;
    }
    .btn {
        border-radius: 0;
    }
</style>

<div class="col-lg-12" id="app">
    <div class="text-center">
        <h1>Registrar Syllabus del curso de Programacion I</h1>
    </div>
</div>

<div class="col-lg-12">

    <div class="col-lg-3 column">
        <div class="row">
            <div class="text-center">
                <h3>Unidades</h3>
                <a class="btn btn-success" @click="add_unidad()" title="Agregar Unidad">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                </a>
            </div>
        </div>

        <div class="row">
            <div class="text-center">
                <div id="unidades">
                    <div class="clickable unidad"
                        id="unidad_@{{ unidad.id }}"
                        v-for="unidad in unidades"
                        @click="select_unidad(unidad)"
                    >
                        <p>@{{ unidad.name }}</p>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-lg-3 column">
        <div class="row">
            <div class="text-center">
                <h3>Semanas</h3>
            </div>
        </div>

        <div class="row">
            <div class="text-center">
                <h4>@{{ unidad_selected.name }}</h4>
                <div id="semanas">
                    <div class="clickable semana"
                         id="semana_@{{ semana.id }}"
                         v-for="semana in unidad_selected.semanas"
                         @click="select_semana(semana)"
                    >
                        <p>@{{ semana.name }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="row">
            <div class="text-center">
                <h3>Temas - Unidad 1 - Semana 1</h3>
                <div id="temas">
                    <div class="clickable tema"
                         id="tema_@{{ tema.id }}"
                         v-for="tema in semana_selected.temas"
                    >
                        <p>@{{ tema.name }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
</div>
<script type="text/javascript">
    var vm = new Vue(
    {
        el: 'body',

        data: {
            unidades: [],
            unidad_selected: {},
            semana_selected: {},
            last_unidad_id: 0,
            last_semana_id: 0,
        },

        methods: {
            select_unidad: function(unidad) {
                var last_unidad = document.getElementById('unidad_' + this.unidad_selected.id)
                var unidad_element = document.getElementById('unidad_' + unidad.id)

                if (this.unidad_selected.id == undefined) {
                    unidad_element.className += ' unidad-selected'
                    this.unidad_selected = unidad
                } else {
                    if (this.unidad_selected.id == unidad.id) {
                        unidad_element.className = 'clickable unidad'
                        this.unidad_selected = {}
                    } else {
                        last_unidad.className = 'clickable unidad'
                        unidad_element.className += ' unidad-selected'
                        this.unidad_selected = unidad
                    }
                }
                this.semana_selected = {}
            },
            select_semana: function(semana) {
                var last_semana = document.getElementById('semana_' + this.semana_selected.id)
                var semana_element = document.getElementById('semana_' + semana.id)

                if (this.semana_selected.id == undefined) {
                    semana_element.className += ' semana-selected'
                    this.semana_selected = semana
                } else {
                    if (this.semana_selected.id == semana.id) {
                        semana_element.className = 'clickable semana'
                        this.semana_selected = {}
                    } else {
                        last_semana.className = 'clickable semana'
                        semana_element.className += ' semana-selected'
                        this.semana_selected = semana
                    }
                }
            },
            add_unidad: function() {
                var new_id = ++this.last_unidad_id
                this.unidades.push({
                    id: new_id,
                    name: 'Unidad ' + new_id
                })
            },
        },

        ready: function()
        {
            this.unidades = ['Unidad 1', 'Unidad 2', 'Unidad 3']

            this.unidades = [
                {
                    id: 1,
                    name: "Unidad 1",
                    semanas : [
                    ],
                },
                {
                    id: 2,
                    name: "Unidad 2",
                    semanas : [
                    ],
                },
            ]
            this.last_unidad_id += 2

            var semanas = [
                {
                    id: 1,
                    name: "Semana 1",
                    temas: [
                        {
                            id: 1,
                            name: 'Introduccion a la Programacion',
                        }
                    ],
                },
                {
                    id: 2,
                    name: "Semana 2",
                },
                {
                    id: 3,
                    name: "Semana 3",
                },
                {
                    id: 4,
                    name: "Semana 4",
                },
            ]

            this.unidades[0].semanas = semanas
            //this.unidad_selected = this.unidades[0]
        }
    });
</script>
@endsection